/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author w8
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        txtFilas.requestFocusInWindow();
        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdAutomatico, cmdManual, cmdOperar};
        Helper.HabilitarBotones(botonesH);
        Helper.DeshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        txtFilas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdLimpiar = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        cmdOperar = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmbRecorrido = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatriz = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recorridos");
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("N° columnas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("N° filas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txtColumnas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColumnasKeyTyped(evt);
            }
        });
        jPanel1.add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, -1));

        txtFilas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilasKeyTyped(evt);
            }
        });
        jPanel1.add(txtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 50, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 60, -1));

        cmdOperar.setText("Operar");
        cmdOperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        cmdAutomatico.setText("Automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, -1));

        cmbRecorrido.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbRecorrido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recorrido 1", "Recorrido 2", "Caracol", "Recorrido Z", "Recorrido M" }));
        jPanel2.add(cmbRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 310, 110));

        tblMatriz.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMatriz.setEnabled(false);
        jScrollPane1.setViewportView(tblMatriz);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 180, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(535, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm;
        int nf = 0, nc = 0;
        int sw = 1;
        tm = (DefaultTableModel) tblMatriz.getModel();
        
        try {
            nf = Integer.parseInt(txtFilas.getText());
            nc = Integer.parseInt(txtColumnas.getText());
        } catch (NumberFormatException e) {
            Helper.mensaje(this, "Por favor digite datos validos", "Error", 2);
            sw = 0;
        }
        
        if (sw == 1) {
            if (nf == 0) {
                Helper.mensaje(this, "No puede ser cero", "Error", 2);
                txtFilas.requestFocusInWindow();
                txtFilas.selectAll();
            } else if (nc == 0) {
                Helper.mensaje(this, "No puede ser cero", "Error", 2);
                txtColumnas.requestFocusInWindow();
                txtColumnas.selectAll();
            } else if (nf > 9) {
                Helper.mensaje(this, "No puede ser mayor a 9", "Error", 2);
                txtFilas.requestFocusInWindow();
                txtFilas.selectAll();
            } else if (nc > 9) {
                Helper.mensaje(this, "No puede ser mayor a 9", "Error", 2);
                txtColumnas.requestFocusInWindow();
                txtColumnas.selectAll();
            } else if (nf < 5) {
                Helper.mensaje(this, "No puede ser menor a 5", "Error", 2);
                txtFilas.requestFocusInWindow();
                txtFilas.selectAll();
            } else if (nc < 5) {
                Helper.mensaje(this, "No puede ser menor a 5", "Error", 2);
                txtColumnas.requestFocusInWindow();
                txtColumnas.selectAll();
            } else {
                tm.setRowCount(nf);
                tm.setColumnCount(nc);
                
                JButton botonesH[] = {cmdLimpiar, cmdAutomatico, cmdManual};
                JButton botonesD[] = {cmdCrear, cmdOperar};
                Helper.HabilitarBotones(botonesH);
                Helper.DeshabilitarBotones(botonesD);
                txtColumnas.setEditable(false);
                txtFilas.setEditable(false);
            }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        // TODO add your handling code here:
        int nf, nc;
        int n;
        nf = tblMatriz.getRowCount();
        nc = tblMatriz.getColumnCount();
        
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 25 + 1);
                tblMatriz.setValueAt(n, i, j);
            }
        }
        JButton botonesH[] = {cmdLimpiar, cmdOperar};
        JButton botonesD[] = {cmdCrear, cmdAutomatico, cmdManual};
        Helper.HabilitarBotones(botonesH);
        Helper.DeshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdOperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperarActionPerformed
        // TODO add your handling code here:
        int op, nf, nc, aux;
        
        op = cmbRecorrido.getSelectedIndex();
        nf = tblMatriz.getRowCount();
        nc = tblMatriz.getColumnCount();
        
        txtResultado.setText("");
        switch (op) {
            case 0:
                if (nf % 2 == 1 && nc % 2 == 1) {
                    if (nf == nc) {
                        txtResultado.setText(Helper.Recorrido1(tblMatriz));
                    } else {
                        Helper.mensaje(this, "Las filas y columnas deben ser iguales", "Error", 2);
                    }
                } else {
                    Helper.mensaje(this, "Las filas y columnas deben ser impares", "Error", 2);
                }
                break;
            case 1:
                if (nf % 2 == 1 && nc % 2 == 1) {
                    if (nf == nc) {
                        txtResultado.setText(Helper.Recorrido2(tblMatriz));
                    } else {
                        Helper.mensaje(this, "Las filas y columnas deben ser iguales", "Error", 2);
                    }
                } else {
                    Helper.mensaje(this, "Las filas y columnas deben ser impares", "Error", 2);
                }
                break;
            case 2:
                if (nf % 2 == 0 && nc % 2 == 0) {
                    if (nf == nc) {
                        txtResultado.setText(Helper.Caracol(tblMatriz));
                    } else {
                        Helper.mensaje(this, "Las filas y columnas deben ser iguales", "Error", 2);
                    }
                } else {
                    Helper.mensaje(this, "Las filas y columnas deben ser pares", "Error", 2);
                }
                break;
            case 3:
                if (nf % 2 == 1 && nc % 2 == 1) {
                    if (nf == nc) {
                        txtResultado.setText(Helper.RecorridoZ(tblMatriz));
                    } else {
                        Helper.mensaje(this, "Las filas y columnas deben ser iguales", "Error", 2);
                    }
                } else {
                    Helper.mensaje(this, "Las filas y columnas deben ser impares", "Error", 2);
                }
                break;
            case 4:
                if (nf % 2 == 1 && nc % 2 == 1) {
                    if (nf == nc) {
                        txtResultado.setText(Helper.RecorridoM(tblMatriz));
                    } else {
                        Helper.mensaje(this, "Las filas y columnas deben ser iguales", "Error", 2);
                    }
                } else {
                    Helper.mensaje(this, "Las filas y columnas deben ser impares", "Error", 2);
                }
                break;
        }
    }//GEN-LAST:event_cmdOperarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        Helper.TablaPorDefecto(tblMatriz);
        
        JButton botonesH[] = {cmdLimpiar, cmdCrear};
        JButton botonesD[] = {cmdOperar, cmdAutomatico, cmdManual};
        Helper.HabilitarBotones(botonesH);
        Helper.DeshabilitarBotones(botonesD);
        txtFilas.setText("");
        txtColumnas.setText("");
        txtFilas.setEditable(true);
        txtColumnas.setEditable(true);
        txtFilas.requestFocusInWindow();
        cmbRecorrido.setSelectedIndex(0);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        // TODO add your handling code here:
        int nf, nc, res, aux;
        double n;
        boolean sw = true;
        nf = tblMatriz.getRowCount();
        nc = tblMatriz.getColumnCount();
        
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                do {
                    aux = 1;
                    try {
                        n = Double.parseDouble(Helper.RecibirDatos(this, "Digite el elemento en la posición: [" + i + "][" + j + "]"));
                        tblMatriz.setValueAt((int) n, i, j);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Digite la información correctamente", "Error", JOptionPane.ERROR_MESSAGE);
                        aux = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Desea Salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        System.out.println(res);
                        if (res == 0) {
                            aux = 1;
                            j = nc;
                            i = nf;
                            sw = false;
                            JButton botonesH[] = {cmdCrear, cmdLimpiar};
                            JButton botonesD[] = {cmdAutomatico, cmdManual, cmdOperar};
                            Helper.HabilitarBotones(botonesH);
                            Helper.DeshabilitarBotones(botonesD);
                            Helper.TablaPorDefecto(tblMatriz);
                        } else {
                            aux = 0;
                            JButton botonesH[] = {cmdOperar, cmdLimpiar};
                            JButton botonesD[] = {cmdAutomatico, cmdManual, cmdCrear};
                            Helper.HabilitarBotones(botonesH);
                            Helper.DeshabilitarBotones(botonesD);
                        }
                        
                    }
                } while (aux == 0);
                
            }
        }
        JButton botonesH[] = {cmdLimpiar, cmdOperar};
        JButton botonesD[] = {cmdCrear, cmdAutomatico, cmdManual};
        Helper.HabilitarBotones(botonesH);
        Helper.DeshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdManualActionPerformed

    private void txtFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtFilasKeyTyped

    private void txtColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtColumnasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRecorrido;
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdOperar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMatriz;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
